# Generated by Django 5.2 on 2025-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
