# Generated by Django 5.2 on 2025-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='manga_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.AddField(
            model_name='history',
            name='mal_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
