# Generated by Django 5.2 on 2025-04-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_history_manga_id_remove_history_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='rating',
        ),
    ]
